2025-02-23 09:00:26 - INFO - PMTfication by part starts...
2025-02-23 09:00:26 - INFO - Processing file: merged_part_9.db
2025-02-23 09:00:26 - INFO - Using up to 40 workers.
2025-02-23 09:00:31 - INFO - Processing shard 1 of part 9 in subdirectory 0004000-0004999.
2025-02-23 09:03:52 - ERROR - An error occurred: no such column: BjorkenX
Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMTfy_by_part.py", line 60, in <module>
    main()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMTfy_by_part.py", line 55, in main
    pmtfier.pmtfy_part(source_part_file=source_file_path)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMTfier.py", line 214, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMTfier.py", line 191, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMTfier.py", line 178, in pmtfy_shard
    pa_truth_shard = truth_maker(int(self.subdir_tag), part_no, shard_no, event_batch)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMT_truth_maker.py", line 63, in __call__
    MCWeightDict_table = self._get_pa_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMT_truth_maker.py", line 144, in _get_pa_shard
    rows, columns = self._execute_query(query)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfication/PMT_truth_maker.py", line 296, in _execute_query
    cursor.execute(query)
sqlite3.OperationalError: no such column: BjorkenX
