nohup: ignoring input
2024-11-29 17:39:08 - INFO - PMTfication starts...
2024-11-29 17:39:08 - INFO - The number of files in the subdirectory: 2
2024-11-29 17:39:08 - INFO - Using up to 1 workers.
2024-11-29 17:39:08 - INFO - Found 2 database files in subdirectory 99999.
Processing 99999:   0%|          | 0/2 [00:00<?, ?it/s]2024-11-29 17:39:09 - INFO - Processing shard 1 of part 98 in subdirectory 99999.
2024-11-29 17:39:10 - ERROR - Error processing file merged_part_98.db: append_column() got an unexpected keyword argument 'type'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 206, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 184, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 158, in pmtfy_shard
    pa_pmtfied = self._add_enhance_event_no(pa_pmtfied, subdir_tag, part_no)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 128, in _add_enhance_event_no
    pa_table = pa_table.append_column('original_event_no', original_event_no, type=pa.int32())
  File "pyarrow/table.pxi", line 2290, in pyarrow.lib._Tabular.append_column
TypeError: append_column() got an unexpected keyword argument 'type'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 250, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
TypeError: append_column() got an unexpected keyword argument 'type'
Processing 99999:  50%|█████     | 1/2 [00:01<00:01,  1.91s/it]2024-11-29 17:39:10 - INFO - Processing shard 1 of part 99 in subdirectory 99999.
2024-11-29 17:39:17 - ERROR - Error processing file merged_part_99.db: append_column() got an unexpected keyword argument 'type'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 206, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 184, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 158, in pmtfy_shard
    pa_pmtfied = self._add_enhance_event_no(pa_pmtfied, subdir_tag, part_no)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 128, in _add_enhance_event_no
    pa_table = pa_table.append_column('original_event_no', original_event_no, type=pa.int32())
  File "pyarrow/table.pxi", line 2290, in pyarrow.lib._Tabular.append_column
TypeError: append_column() got an unexpected keyword argument 'type'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 250, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
TypeError: append_column() got an unexpected keyword argument 'type'
Processing 99999: 100%|██████████| 2/2 [00:08<00:00,  4.91s/it]Processing 99999: 100%|██████████| 2/2 [00:08<00:00,  4.46s/it]
2024-11-29 17:39:17 - INFO - PMTfication completed.
