nohup: ignoring input
2024-11-26 14:34:40 - INFO - PMTfication starts...
2024-11-26 14:34:40 - INFO - The number of files in the subdirectory: 2
2024-11-26 14:34:40 - INFO - Using up to 1 workers.
2024-11-26 14:34:40 - INFO - Found 2 database files in subdirectory 99999.
Processing 99999:   0%|          | 0/2 [00:00<?, ?it/s]2024-11-26 14:34:40 - INFO - Processing shard 1 of part 98 in subdirectory 99999.
2024-11-26 14:34:41 - ERROR - Error processing file merged_part_98.db: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 156, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 72, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 95, in _get_PMTfied_pa
    arrays = {key: value[:] for key, value in PMTSummariser._DEFAULT_ARRAYS.items()}
AttributeError: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 249, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
AttributeError: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
Processing 99999:  50%|█████     | 1/2 [00:00<00:00,  1.33it/s]2024-11-26 14:34:41 - INFO - Processing shard 1 of part 99 in subdirectory 99999.
2024-11-26 14:34:44 - ERROR - Error processing file merged_part_99.db: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 156, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 72, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 95, in _get_PMTfied_pa
    arrays = {key: value[:] for key, value in PMTSummariser._DEFAULT_ARRAYS.items()}
AttributeError: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 249, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
AttributeError: type object 'PMTSummariser' has no attribute '_DEFAULT_ARRAYS'
Processing 99999: 100%|██████████| 2/2 [00:04<00:00,  2.34s/it]Processing 99999: 100%|██████████| 2/2 [00:04<00:00,  2.10s/it]
2024-11-26 14:34:44 - INFO - PMTfication completed.
