nohup: ignoring input
2024-11-26 14:36:46 - INFO - PMTfication starts...
2024-11-26 14:36:46 - INFO - The number of files in the subdirectory: 2
2024-11-26 14:36:46 - INFO - Using up to 1 workers.
2024-11-26 14:36:46 - INFO - Found 2 database files in subdirectory 99999.

Processing 99999:   0%|          | 0/2 [00:00<?, ?it/s]2024-11-26 14:36:46 - INFO - Processing shard 1 of part 98 in subdirectory 99999.
2024-11-26 14:36:47 - ERROR - Error processing file merged_part_98.db: dom_data length does not match schema
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 156, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 77, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 107, in _get_PMTfied_pa
    raise ValueError("dom_data length does not match schema")
ValueError: dom_data length does not match schema
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 249, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
ValueError: dom_data length does not match schema

Processing 99999:  50%|█████     | 1/2 [00:00<00:00,  1.33it/s]2024-11-26 14:36:47 - INFO - Processing shard 1 of part 99 in subdirectory 99999.
2024-11-26 14:36:51 - ERROR - Error processing file merged_part_99.db: dom_data length does not match schema
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 205, in pmtfy_part
    consolidated_truth = self._divide_and_conquer_part(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 183, in _divide_and_conquer_part
    pa_truth_shard = self.pmtfy_shard(
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 156, in pmtfy_shard
    pa_pmtfied = summariser()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 77, in __call__
    return self._get_PMTfied_pa()
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMT_summariser.py", line 107, in _get_PMTfied_pa
    raise ValueError("dom_data length does not match schema")
ValueError: dom_data length does not match schema
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/hpc/icecube/cyan/factory/DOMification/PMTfier.py", line 249, in pmtfy_subdir_parallel
    future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
ValueError: dom_data length does not match schema

Processing 99999: 100%|██████████| 2/2 [00:04<00:00,  2.31s/it]
Processing 99999: 100%|██████████| 2/2 [00:04<00:00,  2.08s/it]
DEBUG: Schema length: 31
DEBUG: Schema fields: ['event_no', 'dom_x', 'dom_y', 'dom_z', 'dom_x_rel', 'dom_y_rel', 'dom_z_rel', 'pmt_area', 'rde', 'saturation_status', 'q1', 'q2', 'q3', 'q4', 'q5', 'Q25', 'Q75', 'Qtotal', 'hlc1', 'hlc2', 'hlc3', 'hlc4', 'hlc5', 't1', 't2', 't3', 't4', 't5', 'T10', 'T50', 'sigmaT']
DEBUG: dom_data length: 29
DEBUG: dom_data: [1419, 124.97, -131.25, 476.63, -158.00124288937806, -400.0393708829479, 152.7500302146351, 0.0444, 1.0, -1.0, -0.07796152847411307, -1.0, -1.0, -0.07796152847411307, -0.07796152847411307, -0.07796152847411307, 0, -1, -1, -1, -1, 12716.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1]
DEBUG: Schema length: 31
DEBUG: Schema fields: ['event_no', 'dom_x', 'dom_y', 'dom_z', 'dom_x_rel', 'dom_y_rel', 'dom_z_rel', 'pmt_area', 'rde', 'saturation_status', 'q1', 'q2', 'q3', 'q4', 'q5', 'Q25', 'Q75', 'Qtotal', 'hlc1', 'hlc2', 'hlc3', 'hlc4', 'hlc5', 't1', 't2', 't3', 't4', 't5', 'T10', 'T50', 'sigmaT']
DEBUG: dom_data length: 29
DEBUG: dom_data: [366, -256.14, -521.08, -474.15, -43.46077476778922, -542.9430548264415, -338.5627419758743, 0.0444, 1.0, 0.0, -0.7444404872853159, -1.0, -1.0, -0.7444404872853159, -0.7444404872853159, -0.7444404872853159, 1, -1, -1, -1, -1, 17873.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1]
2024-11-26 14:36:51 - INFO - PMTfication completed.
